name = "LeanSortedFinsupp"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanSortedFinsupp"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "lean4export"
scope = "leanprover"

[[require]]
name = "groebner"
scope = "WuProver"

[[lean_lib]]
name = "LeanSortedFinsupp"

